name: My Custom Action
description: Deploy to Target Environment
inputs:
  target:
    description: 'Target environment'
    required: true
    default: 'test'
  environment:
    description: 'Deployment environment'
    required: true
    default: 'dev'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Build and Test
      run: go build && go test -v ./...

    - name: Deploy to Target Environment
      run: |
        if [ "${{ inputs.target }}" = "test" ]; then
          if [ "${{ inputs.environment }}" = "dev" ]; then
            ./scripts/deploy-test-dev.sh
          elif [ "${{ inputs.environment }}" = "stage" ]; then
            ./scripts/deploy-test-stage.sh
          elif [ "${{ inputs.environment }}" = "prod" ]; then
            ./scripts/deploy-test-prod.sh
          fi
        elif [ "${{ inputs.target }}" = "stage" ]; then
          if [ "${{ inputs.environment }}" = "dev" ]; then
            ./scripts/deploy-stage-dev.sh
          elif [ "${{ inputs.environment }}" = "stage" ]; then
            ./scripts/deploy-stage-stage.sh
          elif [ "${{ inputs.environment }}" = "prod" ]; then
            ./scripts/deploy-stage-prod.sh
          fi
        elif [ "${{ inputs.target }}" = "prod" ]; then
          if [ "${{ inputs.environment }}" = "dev" ]; then
            ./scripts/deploy-prod-dev.sh
          elif [ "${{ inputs.environment }}" = "stage" ]; then
            ./scripts/deploy-prod-stage.sh
          elif [ "${{ inputs.environment }}" = "prod" ]; then
            ./scripts/deploy-prod-prod.sh
          fi
        fi
