name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  ci_cd:
    name: Continuous Integration and Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build and Test
        run: go build && go test -v ./...

      - name: Deploy to Test Environment
        env:
          TARGET: test
          ENVIRONMENT: development
        run: go run main.go

      - name: Deploy to Stage Environment
        env:
          TARGET: stage
          ENVIRONMENT: staging
        run: go run main.go

      - name: Deploy to Production Environment
        env:
          TARGET: production
          ENVIRONMENT: production
        run: go run main.go
